# Site settings
title: ailin liao
email: ailinliao1022@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hello world!
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: ailinbot
github_username:  ailinliao

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
